services:
  postgres:
    image: postgres:17-alpine
    container_name: github-search-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-github_search}
      POSTGRES_USER: ${DATABASE_USERNAME:-github}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-github}
    ports:
      - '5432:5432'
    networks:
      - app-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DATABASE_USERNAME:-github} -d ${DATABASE_NAME:-github_search}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-api:
    build:
      context: .
      dockerfile: apps/auth-api/Dockerfile
    container_name: github-search-auth-api
    restart: unless-stopped
    env_file:
      - .env.docker.example
    environment:
      SERVICE_NAME: auth-api
      NODE_ENV: test
      API_GATEWAY_PORT: 3000
      AUTH_SERVICE_HOST: 0.0.0.0
      AUTH_SERVICE_PORT: 3001
      GITHUB_SERVICE_HOST: github-api
      GITHUB_SERVICE_PORT: 3002
      DATABASE_TYPE: postgres
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-github}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-github}
      DATABASE_NAME: ${DATABASE_NAME:-github_search}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE:-true}
      DATABASE_SSL: ${DATABASE_SSL:-}
      JWT_SECRET: ${JWT_SECRET:-changeme}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-1h}
      GITHUB_API_URL: https://api.github.com
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN:-}
    ports:
      - '3001:3001'
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('net').createConnection({host:'localhost',port:3001}).on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  github-api:
    build:
      context: .
      dockerfile: apps/github-api/Dockerfile
    container_name: github-search-github-api
    restart: unless-stopped
    env_file:
      - .env.docker.example
    environment:
      SERVICE_NAME: github-api
      NODE_ENV: test
      API_GATEWAY_PORT: 3000
      AUTH_SERVICE_HOST: auth-api
      AUTH_SERVICE_PORT: 3001
      GITHUB_SERVICE_HOST: 0.0.0.0
      GITHUB_SERVICE_PORT: 3002
      DATABASE_TYPE: postgres
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-github}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-github}
      DATABASE_NAME: ${DATABASE_NAME:-github_search}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE:-true}
      DATABASE_SSL: ${DATABASE_SSL:-}
      JWT_SECRET: ${JWT_SECRET:-changeme}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-1h}
      GITHUB_API_URL: https://api.github.com
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN:-}
    ports:
      - '3002:3002'
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('net').createConnection({host:'localhost',port:3002}).on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: github-search-api-gateway
    restart: unless-stopped
    env_file:
      - .env.docker.example
    environment:
      SERVICE_NAME: api-gateway
      NODE_ENV: test
      API_GATEWAY_PORT: 3000
      AUTH_SERVICE_HOST: auth-api
      AUTH_SERVICE_PORT: 3001
      GITHUB_SERVICE_HOST: github-api
      GITHUB_SERVICE_PORT: 3002
      DATABASE_TYPE: postgres
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-github}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-github}
      DATABASE_NAME: ${DATABASE_NAME:-github_search}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE:-true}
      DATABASE_SSL: ${DATABASE_SSL:-}
      JWT_SECRET: ${JWT_SECRET:-changeme}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-1h}
      GITHUB_API_URL: https://api.github.com
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN:-}
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      auth-api:
        condition: service_started
      github-api:
        condition: service_started
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:3000/api/docs || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
